### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by firasdib** [Kamil93/pcre2#1]
I get a permission denied error when trying to install.

```
firas@dev:~/test$ npm i pcre2

> pcre2@0.0.4-a install /home/firas/test/node_modules/pcre2
> node-gyp rebuild

make: Entering directory '/home/firas/test/node_modules/pcre2/build'
  ACTION Building PCRE2 library... .
/bin/sh: 1: eval: ./compile: Permission denied
pcre2.target.mk:13: recipe for target '.' failed
make: *** [.] Error 126
make: Leaving directory '/home/firas/test/node_modules/pcre2/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:135:13)
gyp ERR! stack     at ChildProcess.emit (events.js:224:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/firas/test/node_modules/pcre2
gyp ERR! node -v v9.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```

**Comment by ualnwe** [comment]
In case there's people coming to this for a fix, I managed to work around the issue by Ctrl-C ing the install before the `node-gyp rebuild` and manually running the commands from the compile file.

The issue for me was that it used `/bin/sh` instead of `/bin/bash` and `gmake` instead of `make`

You may need to install node-gyp, but after manually running the commands, a `node-gyp rebuild` inside `/node_modules/pcre2/` then works correctly.
